#!/usr/bin/env bash
# ===========================================================================
# Heroku prebuild step for the ring-sig wasm artifacts.
#
# Why this exists: the UI's `package.json` has a file dep
#   "ring-sig-wasm": "file:../ring-sig/wasm/pkg-bundler"
# pointing at a directory that's gitignored because it's generated by
# `wasm-pack` from the Rust source. On Heroku, after `git clone` the
# directory doesn't exist, npm creates a broken symlink, and `tsc -b`
# fails with `Cannot find module 'ring-sig-wasm'`.
#
# Heroku runs `npm run heroku-prebuild` BEFORE `npm install`, which is
# the perfect place to install Rust + wasm-pack and build the wasm
# artifacts. After this script finishes, both
#   packages/ring-sig/wasm/pkg/          (nodejs target, used by api)
#   packages/ring-sig/wasm/pkg-bundler/  (bundler target, used by ui)
# exist on disk, and the subsequent `npm install` resolves the file
# deps correctly.
#
# Build cost: ~3-5 minutes added to each Heroku deploy (Rust install
# is ~1 min, wasm-pack install ~30s, the actual wasm build ~30s).
# This can be reduced to <30s by adding cacheDirectories for the
# Rust toolchain — see the README "Deploying to Heroku" section.
#
# Locally: this script is harmless to run. If `cargo` and `wasm-pack`
# are already installed it skips the install steps and just rebuilds
# the wasm artifacts.
# ===========================================================================
set -euo pipefail

# Fast path: if both wasm output directories already exist on disk
# (e.g. they were committed by a CI build before deploy), skip the
# Rust install entirely. This makes Heroku deploys ~30s instead of
# ~5min when wasm is pre-built upstream.
if [ -d packages/ring-sig/wasm/pkg-bundler ] && \
   [ -d packages/ring-sig/wasm/pkg ] && \
   [ -f packages/ring-sig/wasm/pkg-bundler/package.json ] && \
   [ -f packages/ring-sig/wasm/pkg/package.json ]; then
  echo "===> heroku-prebuild: wasm artifacts already present, skipping Rust install"
  exit 0
fi

echo "===> heroku-prebuild: ensuring Rust toolchain"
if ! command -v cargo >/dev/null 2>&1; then
  echo "     installing rustup (stable, minimal profile)"
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
    | sh -s -- -y --default-toolchain stable --profile minimal --no-modify-path
fi

# rustup-init writes to ~/.cargo/env but doesn't touch the current
# shell's PATH. Add it explicitly so wasm-pack and cargo are visible
# for the rest of the script.
if [ -f "$HOME/.cargo/env" ]; then
  # shellcheck disable=SC1091
  . "$HOME/.cargo/env"
fi
export PATH="$HOME/.cargo/bin:$PATH"

echo "===> heroku-prebuild: ensuring wasm-pack"
if ! command -v wasm-pack >/dev/null 2>&1; then
  echo "     installing wasm-pack (precompiled binary)"
  curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
fi

# Re-export PATH in case wasm-pack just landed in ~/.cargo/bin
export PATH="$HOME/.cargo/bin:$PATH"

echo "===> heroku-prebuild: building ring-sig-wasm bundler target (for the UI)"
wasm-pack build packages/ring-sig/wasm \
  --target bundler --out-dir pkg-bundler --release

echo "===> heroku-prebuild: building ring-sig-wasm nodejs target (for the api)"
wasm-pack build packages/ring-sig/wasm \
  --target nodejs --out-dir pkg --release

echo "===> heroku-prebuild: done"
echo "     pkg/         $(ls packages/ring-sig/wasm/pkg/ 2>/dev/null | wc -l) files"
echo "     pkg-bundler/ $(ls packages/ring-sig/wasm/pkg-bundler/ 2>/dev/null | wc -l) files"
